### ISSUE TITLE
Support for guzzlehttp/guzzle ^7.0

### ISSUE THREAD

**Issue by markdwhite** [drunomics/php-paapi5-sdk#1]
Any chance we could bump composer.json to

    "guzzlehttp/guzzle" : "^6.2 | ^7.0"

There's nothing used in php-paapi5-sdk that uses anything that breaks across the major version upgrade, so this should be clean, and will allow more compatibility with other packages.

Thanks.

**Comment by mbm80** [comment]
done, created 1.0.1
