### ISSUE TITLE
Incompatible with guzzlehttp/psr7 2.0.0

### ISSUE THREAD

**Issue by neildaniels** [drunomics/php-paapi5-sdk#4]
The https://github.com/drunomics/php-paapi5-sdk/blob/master/src/com/amazon/paapi5/v1/api/DefaultApi.php uses `\GuzzleHttp\Psr7\build_query()` in various places.

This function (along with others) was removed in `guzzlehttp/psr7` 2.0.0, which was released about 22 days ago.

I doubt Amazon will update the original file, so it would make sense to specify 1.x version in the composer file.

```json
"guzzlehttp/psr7": "^1.8.2"
```

**Comment by mbm80** [comment]
makes sense, added & created 1.1.2
